name: Push to EC2
on: push

jobs:
  Ec2-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME  }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }} 
          command: |
                  sudo systemctl daemon-reload
                  sudo systemctl restart test.service

